In [4]:
!nvidia-smi

Thu Jan 30 14:28:14 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 561.19                 Driver Version: 561.19         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   45C    P0             14W /  140W |       0MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [86]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import IPython

print(torch.__version__)
print(torch.cuda.is_available())
print(IPython.version_info)

2.4.1
True
(8, 12, 2, '')


## Introduction to Tensors

### Creating Tensors

In [6]:
# scalar

scalar = torch.tensor(7)

scalar

tensor(7)

In [7]:
scalar.ndim


0

In [8]:
#Get tensor back as python integer

scalar.item()

7

In [9]:
#Vector

vector = torch.tensor([7, 7])

vector

tensor([7, 7])

In [10]:
vector.ndim  #(rank 1 tensor, think of it like the number of pairs of square brackets)

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
#Matrix

MATRIX = torch.tensor([
    [7, 8],
    [9, 10]
])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
rectangle_matrix = torch.tensor([
    [7, 8],
    [9, 10],
    [11, 12]
])
rectangle_matrix


tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [16]:
print(rectangle_matrix.ndim)

# Shape = (Rows, Cols)
print(rectangle_matrix.shape)

2
torch.Size([3, 2])


In [17]:
MATRIX[0]

tensor([7, 8])

In [18]:
#Tensor

TENSOR = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [10, 11, 12]
    ]
])

TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [19]:
print(TENSOR.ndim)

# Shape = (Number of matrices ,Rows, Cols)
print(TENSOR.shape)

3
torch.Size([1, 4, 3])


In [20]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [21]:
#Doesnt work because we have only 1 matrix which is at index 0
# TENSOR[1]

In [22]:
TENSOR_2 = torch.tensor([  #Contains array of matrices
    [  # Contains array of vectors (arrays)
        [1, 2, 3],  # Array of integers
        [4, 5, 6],
        [7, 8, 9],
        [10, 11, 12]
    ],

    [  # Contains array of vectors (arrays)
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]
    ]
])

# (2,4,3)
# Basically saying we have 2 matrices with 4 rows and 3 cols
print(TENSOR_2.shape)

torch.Size([2, 4, 3])


In [23]:
TENSOR_3 = torch.tensor(
    [  # Contains array of tensors
        [  #Contains array of matrices
            [  # Contains array of vectors (arrays)
                [1, 2, 3],  # Array of integers
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]
            ],

            [  # Contains array of vectors (arrays)
                [13, 14, 15],
                [16, 17, 18],
                [19, 20, 21],
                [22, 23, 24]
            ]
        ]
    ])

print(TENSOR_3.shape)
print(TENSOR_3[0])
print(TENSOR_3[0][0])
print(TENSOR_3[0][0][0])

torch.Size([1, 2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
tensor([1, 2, 3])


In [24]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [25]:
MATRIX.is_cuda

False

In [26]:
MATRIX.transpose(1, 0)
#or 
# MATRIX.T

tensor([[ 7,  9],
        [ 8, 10]])

In [27]:
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [28]:
TENSOR.transpose(0, 2)

tensor([[[ 1],
         [ 4],
         [ 7],
         [10]],

        [[ 2],
         [ 5],
         [ 8],
         [11]],

        [[ 3],
         [ 6],
         [ 9],
         [12]]])

In [29]:
TENSOR.transpose(0, 1)

tensor([[[ 1,  2,  3]],

        [[ 4,  5,  6]],

        [[ 7,  8,  9]],

        [[10, 11, 12]]])

## Random Tensors

We require random numbers because neural networks start off their learning with random weights and biases which are then adjusted to the represent the patterns/features they learn.


Random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html


In [30]:
#Create a random tensor of shape (3,4)

random_tensor = torch.rand(3, 4)

random_tensor

tensor([[0.8810, 0.5530, 0.5595, 0.4021],
        [0.4754, 0.4634, 0.2049, 0.7497],
        [0.5093, 0.9752, 0.7562, 0.9195]])

In [31]:
random_3d_tensor = torch.rand(2, 4, 5)

print(random_3d_tensor.shape)

random_3d_tensor

torch.Size([2, 4, 5])


tensor([[[0.9488, 0.3734, 0.0991, 0.4139, 0.3502],
         [0.0233, 0.3716, 0.5439, 0.9627, 0.7889],
         [0.8625, 0.9489, 0.8616, 0.4490, 0.8687],
         [0.0756, 0.1656, 0.1596, 0.8637, 0.6813]],

        [[0.4718, 0.3087, 0.9513, 0.8136, 0.7543],
         [0.6521, 0.7340, 0.2453, 0.9773, 0.2707],
         [0.7087, 0.0648, 0.6371, 0.6141, 0.5238],
         [0.6217, 0.7977, 0.6362, 0.0059, 0.2956]]])

In [32]:
#Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3, 224, 224))  #colour channels (R, G, B), height, width 

print(random_image_size_tensor.shape)
random_image_size_tensor

torch.Size([3, 224, 224])


tensor([[[0.2250, 0.0295, 0.3316,  ..., 0.5254, 0.5097, 0.9568],
         [0.5764, 0.5374, 0.8838,  ..., 0.6957, 0.5328, 0.2971],
         [0.4096, 0.0825, 0.4375,  ..., 0.9112, 0.1718, 0.7059],
         ...,
         [0.7249, 0.0223, 0.5283,  ..., 0.0585, 0.9576, 0.6809],
         [0.8274, 0.6341, 0.9565,  ..., 0.1247, 0.0313, 0.4002],
         [0.1264, 0.9702, 0.9987,  ..., 0.4841, 0.8373, 0.6516]],

        [[0.7373, 0.9817, 0.1425,  ..., 0.3842, 0.8528, 0.3282],
         [0.5515, 0.6865, 0.2116,  ..., 0.7440, 0.5108, 0.1539],
         [0.9998, 0.8855, 0.3449,  ..., 0.0800, 0.0617, 0.0546],
         ...,
         [0.7363, 0.1976, 0.8504,  ..., 0.9363, 0.2381, 0.4032],
         [0.7280, 0.4368, 0.8271,  ..., 0.6575, 0.1426, 0.9611],
         [0.1220, 0.8217, 0.0671,  ..., 0.3492, 0.4049, 0.0212]],

        [[0.1575, 0.9088, 0.0489,  ..., 0.6959, 0.0596, 0.0789],
         [0.8476, 0.5005, 0.2292,  ..., 0.2623, 0.2793, 0.7157],
         [0.5131, 0.4688, 0.2495,  ..., 0.0819, 0.0054, 0.

## Zeros and ones

In [33]:
zeros_3d = torch.zeros(size=(3, 4, 4))
zeros_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [34]:
zeros = torch.zeros(size=(3, 4))

zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
ones = torch.ones(size=(3, 4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
#default data type for tensors
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [37]:
# Use torch.range

two_to_20 = torch.arange(2, 21)

two_to_20

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20])

In [38]:
torch.arange(start=0, end=100, step=2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [39]:
torch.arange(start=0, end=102, step=2)

tensor([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
         28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,
         56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,
         84,  86,  88,  90,  92,  94,  96,  98, 100])

### Creating tensors like

In [40]:
# Creating a tensor like the shape of another tensor

tensor_like_twenty = torch.zeros_like(input=two_to_20)

tensor_like_twenty

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
tensor_like_3d_random = torch.rand_like(input=random_tensor)

tensor_like_3d_random

tensor([[0.5173, 0.7379, 0.1209, 0.7032],
        [0.1635, 0.1624, 0.3338, 0.0249],
        [0.2138, 0.2098, 0.0867, 0.4606]])

In [42]:
#doesnt work because rand requires float not int
# torch.rand_like(input=TENSOR_2)

torch.ones_like(input=TENSOR_2)


tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]])

## Tensor Datatypes

**Note:** Dtype is one 3 common errors when running PyTorch for DL
1. Tensor is not right dtype
2. Tensor not right shape
3. Tensor not on right device 

In [43]:
float_32_tensor = torch.tensor([3.0, 6.0], dtype=None)

float_32_tensor

tensor([3., 6.])

In [44]:

#Still shows dtype as float because its the default dtype in torch
float_32_tensor.dtype

torch.float32

In [45]:
all_param_tensor = torch.tensor([
    [6, 7],
    [8, 9]
], dtype=None,  # datatype of data in the tensor
    device=None,  # default is cpu,could be changed to cuda
    requires_grad=False  # If you want the tensor to track gradients when the values are updated
)

In [46]:
float_16_tensor = float_32_tensor.type(torch.half)
# or
# float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6.], dtype=torch.float16)

In [47]:
#type casted to higher capacity dtype
(float_32_tensor * float_16_tensor).dtype

torch.float32

In [48]:
int_32_tensor = torch.tensor([3, 6], dtype=torch.int32)
int_32_tensor

tensor([3, 6], dtype=torch.int32)

In [49]:
float_32_tensor * int_32_tensor

tensor([ 9., 36.])

In [50]:
long_tensor = torch.tensor(data=([3, 6]), dtype=torch.long)
long_tensor

tensor([3, 6])

In [51]:
float_32_tensor * long_tensor

tensor([ 9., 36.])

### Getting info from tensor

1. Tensor is not right dtype - to get dtype from a tensor - use `tensor.dtype` 
2. Tensor not right shape - to get shape, use `tensor.shape`
3. Tensor not on right device - to get which device tensor is on, use `tensor.device` 

In [52]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2825, 0.0011, 0.5270, 0.4509],
        [0.2964, 0.9900, 0.5571, 0.0407],
        [0.9231, 0.6536, 0.2150, 0.4606]])

In [53]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.2825, 0.0011, 0.5270, 0.4509],
        [0.2964, 0.9900, 0.5571, 0.0407],
        [0.9231, 0.6536, 0.2150, 0.4606]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


In [54]:
#Note tensor shape and size are the same
#Size is just a func, while shape is an attribute

some_tensor.shape, some_tensor.size()

(torch.Size([3, 4]), torch.Size([3, 4]))

In [55]:
gpu_tensor = torch.rand(3, 4, device=torch.device('cuda'))



## Manipulating Tensors (Tensor Operations)

Ops include:
* Addition
* Subtraction
* Element-wise multiplication
* Matrix multiplication
* Division

In [56]:
test_tensor = torch.tensor(data=([1, 2, 3]))
test_tensor + 10

tensor([11, 12, 13])

In [57]:
test_tensor - 10

tensor([-9, -8, -7])

In [58]:
test_tensor * 10

tensor([10, 20, 30])

In [59]:
test_tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [60]:
test_tensor // 10

tensor([0, 0, 0])

In [61]:
torch.multiply(test_tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two main ways of multiplication:
1. Element-wise multiplication (e.g. matrix * scalar)
2. Matrix multiplication (dot product => a . b)

Matrix multiplication rules
1. The **inner dimensions** must match: 
* `(3,2) @ (3,2)` wont work
* `(3,2) @ (2,3)` will work
* `(2,3) @ (3,2)` will work
2. The resulting matrix will have the shape of the **outer dimensions**:
* `(3,2) @ (2,3)` -> `(3,3)`
* `(2,3) @ (3,2)` -> `(2,2)`

Generalizing:
**mxn.nxp = mxp**

cols of first matrix = rows of second matrix
Result will have rows of first and cols of second

In [73]:
mul_tensor = torch.tensor(data=(
    [1, 2, 3],
    [4, 5, 6])
)

mul_tensor_2 = torch.tensor(data=(
    [7, 8],
    [10, 11],
    [13, 14])
)

In [74]:
#Element-wise multiplication
print(mul_tensor, "*", mul_tensor)
print(f"Equals: {mul_tensor * mul_tensor}")

# Cant multiply element-wise because shape mismatch
# print(f"Equals: {mul_tensor * mul_tensor_2}")

tensor([[1, 2, 3],
        [4, 5, 6]]) * tensor([[1, 2, 3],
        [4, 5, 6]])
Equals: tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [75]:
#Matrix multiplication
torch.matmul(input=mul_tensor, other=mul_tensor_2)

tensor([[ 66,  72],
        [156, 171]])

In [76]:
torch.matmul(input=mul_tensor_2, other=mul_tensor)

tensor([[ 39,  54,  69],
        [ 54,  75,  96],
        [ 69,  96, 123]])

In [77]:
tensor_sca_1 = torch.tensor(data=([1, 2, 3]))



tensor(14)

In [92]:
%%time
#Doesnt show it here but this is way faster for big tensor multiplications than a for loop
torch.matmul(tensor_sca_1, tensor_sca_1)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [93]:
%%time 
#Has to be first thing in cell
# The above cell is basically only doing a dot product between 2 vectors
sum = 0
for i in tensor_sca_1:
    sum += i * i
sum

# 1*1 + 2*2 + 3*3 

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [94]:
# Another way of saying mat mul
tensor_sca_1 @ tensor_sca_1

tensor(14)

In [78]:
#This is working because it is being treated as a vector instead of a matrix
# If it considered it as a matrix of 1,3 then it would give an error
tensor_sca_1.shape

torch.Size([3])

In [79]:
shape_2_vector = torch.tensor(data=[[1, 2, 3]])
shape_2_vector.shape

torch.Size([1, 3])

In [80]:
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x3 and 1x3)
# torch.matmul(shape_2_vector, shape_2_vector)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x3 and 1x3)

In [81]:
# This works because it transposed the second vector making it 3x1
torch.matmul(shape_2_vector, shape_2_vector.T)

tensor([[14]])

#### One of the most common errors in DL : Shape errors

In [98]:
# Shapes for Matrix multiplication
Tensor_A = torch.tensor(data=[[1, 2, ],
                              [4, 5, ],
                              [7, 8, ]])

Tensor_B = torch.tensor(data=[[1, 2, ],
                              [3, 4, ],
                              [5, 6, ]])

In [99]:
Tensor_A.shape, Tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

Inner dimensions are different so cant multiply 

To fix our issue, we can **transpose** one of our matrices

A **transpose** switches the dimensions of our matrix

In [100]:
Tensor_B.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [101]:
Tensor_B

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [103]:
Tensor_B.shape,Tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [106]:
torch.matmul(Tensor_A, Tensor_B.T)

tensor([[ 5, 11, 17],
        [14, 32, 50],
        [23, 53, 83]])

In [107]:
torch.matmul(Tensor_A, Tensor_B.T).shape

torch.Size([3, 3])