# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

print(torch.__version__)
print(torch.cuda.is_available())

# Create random tensor
tensor1 = torch.rand(size=(7, 7))

tensor1


2.4.1
True


tensor([[0.9381, 0.5405, 0.3103, 0.5467, 0.7911, 0.7628, 0.5214],
        [0.2652, 0.5696, 0.7035, 0.5666, 0.3763, 0.0703, 0.1735],
        [0.4547, 0.4905, 0.6449, 0.8125, 0.3194, 0.4993, 0.7559],
        [0.1185, 0.3619, 0.2433, 0.1944, 0.0170, 0.2385, 0.0921],
        [0.7147, 0.7763, 0.0751, 0.9930, 0.4933, 0.1408, 0.6396],
        [0.9977, 0.8649, 0.4802, 0.9959, 0.0881, 0.0368, 0.4736],
        [0.4753, 0.5239, 0.7569, 0.5710, 0.3581, 0.5479, 0.0736]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
tensor2 = torch.rand(size=(1, 7))

# Perform matrix multiplication 
torch.matmul(tensor1, tensor2.T)

tensor([[2.2272],
        [1.5299],
        [2.0233],
        [0.6981],
        [2.3116],
        [2.6905],
        [1.8122]])

In [6]:
#Also can be done
torch.matmul(tensor1, torch.permute(tensor2, dims=(1, 0)))

tensor([[2.2272],
        [1.5299],
        [2.0233],
        [0.6981],
        [2.3116],
        [2.6905],
        [1.8122]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [8]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
tensor3 = torch.rand(size=(7, 7))
tensor4 = torch.rand(size=(1, 7))

# Matrix multiply tensors
torch.matmul(tensor3, tensor4.T)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [9]:
# Set random seed on the GPU
torch.cuda.manual_seed(RANDOM_SEED)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [10]:
# Set random seed
torch.manual_seed(RANDOM_SEED)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Create two random tensors on GPU
gpu_tensor1 = torch.rand(size=(2, 3), device=device)
gpu_tensor2 = torch.rand(size=(2, 3), device='cpu')
gpu_tensor2 = gpu_tensor2.to(device)

print(gpu_tensor1, gpu_tensor1.device)
print(gpu_tensor2, gpu_tensor2.device)


tensor([[0.3990, 0.5167, 0.0249],
        [0.9401, 0.9459, 0.7967]], device='cuda:0') cuda:0
tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]], device='cuda:0') cuda:0



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [13]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(gpu_tensor1, gpu_tensor2.T)
result

tensor([[0.5972, 0.2273],
        [1.2636, 0.9201]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [16]:
# Find max
print(torch.max(result))
# Find min
print(torch.min(result))


tensor(1.2636, device='cuda:0')
tensor(0.2273, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
# Find arg max
print(torch.argmax(result))

# Find arg min
print(torch.argmin(result))

tensor(2, device='cuda:0')
tensor(1, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [19]:
# Set seed
torch.manual_seed(7)

# Create random tensor
rand_tensor = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
squeezedTensor = torch.squeeze(rand_tensor)


# Print out tensors and their shapes
print(rand_tensor,rand_tensor.shape)
print(squeezedTensor,squeezedTensor.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
