In [2]:
from sympy.codegen.ast import float32
!nvidia-smi

Fri Jan 31 13:02:35 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 561.19                 Driver Version: 561.19         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   45C    P0             14W /  140W |       0MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import IPython

print(torch.__version__)
print(torch.cuda.is_available())
print(IPython.version_info)

2.4.1
True
(8, 12, 2, '')


## Introduction to Tensors

### Creating Tensors

In [4]:
# scalar

scalar = torch.tensor(7)

scalar

tensor(7)

In [5]:
scalar.ndim


0

In [6]:
#Get tensor back as python integer

scalar.item()

7

In [7]:
#Vector

vector = torch.tensor([7, 7])

vector

tensor([7, 7])

In [8]:
vector.ndim  #(rank 1 tensor, think of it like the number of pairs of square brackets)

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#Matrix

MATRIX = torch.tensor([
    [7, 8],
    [9, 10]
])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
rectangle_matrix = torch.tensor([
    [7, 8],
    [9, 10],
    [11, 12]
])
rectangle_matrix


tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [14]:
print(rectangle_matrix.ndim)

# Shape = (Rows, Cols)
print(rectangle_matrix.shape)

2
torch.Size([3, 2])


In [15]:
MATRIX[0]

tensor([7, 8])

In [16]:
#Tensor

TENSOR = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [10, 11, 12]
    ]
])

TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [17]:
print(TENSOR.ndim)

# Shape = (Number of matrices ,Rows, Cols)
print(TENSOR.shape)

3
torch.Size([1, 4, 3])


In [18]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [19]:
#Doesnt work because we have only 1 matrix which is at index 0
# TENSOR[1]

In [20]:
TENSOR_2 = torch.tensor([  #Contains array of matrices
    [  # Contains array of vectors (arrays)
        [1, 2, 3],  # Array of numbers
        [4, 5, 6],
        [7, 8, 9],
        [10, 11, 12]
    ],

    [  # Contains array of vectors (arrays)
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]
    ]
])

# (2,4,3)
# Basically saying we have 2 matrices with 4 rows and 3 cols
print(TENSOR_2.shape)

torch.Size([2, 4, 3])


In [21]:
TENSOR_3 = torch.tensor(
    [  # Contains array of tensors
        [  #Contains array of matrices
            [  # Contains array of vectors (arrays)
                [1, 2, 3],  # Array of integers
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]
            ],

            [  # Contains array of vectors (arrays)
                [13, 14, 15],
                [16, 17, 18],
                [19, 20, 21],
                [22, 23, 24]
            ]
        ]
    ])

print(TENSOR_3.shape)
print(TENSOR_3[0])
print(TENSOR_3[0][0])
print(TENSOR_3[0][0][0])

torch.Size([1, 2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
tensor([1, 2, 3])


In [22]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [23]:
MATRIX.is_cuda

False

In [24]:
MATRIX.transpose(1, 0)
#or 
# MATRIX.T

tensor([[ 7,  9],
        [ 8, 10]])

In [25]:
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [26]:
TENSOR.transpose(0, 2)

tensor([[[ 1],
         [ 4],
         [ 7],
         [10]],

        [[ 2],
         [ 5],
         [ 8],
         [11]],

        [[ 3],
         [ 6],
         [ 9],
         [12]]])

In [27]:
TENSOR.transpose(0, 1)

tensor([[[ 1,  2,  3]],

        [[ 4,  5,  6]],

        [[ 7,  8,  9]],

        [[10, 11, 12]]])

## Random Tensors

We require random numbers because neural networks start off their learning with random weights and biases which are then adjusted to the represent the patterns/features they learn.


Random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html


In [28]:
#Create a random tensor of shape (3,4)

random_tensor = torch.rand(3, 4)

random_tensor

tensor([[0.1598, 0.0508, 0.6811, 0.0967],
        [0.1238, 0.5560, 0.3790, 0.5016],
        [0.9301, 0.0153, 0.1698, 0.4644]])

In [29]:
random_3d_tensor = torch.rand(2, 4, 5)

print(random_3d_tensor.shape)

random_3d_tensor

torch.Size([2, 4, 5])


tensor([[[0.7086, 0.0733, 0.5688, 0.5559, 0.4662],
         [0.4953, 0.7827, 0.4712, 0.8054, 0.4218],
         [0.3185, 0.5141, 0.2404, 0.7458, 0.7792],
         [0.9021, 0.7271, 0.4946, 0.1188, 0.9285]],

        [[0.3414, 0.8827, 0.7041, 0.8942, 0.3321],
         [0.2499, 0.7503, 0.5765, 0.0512, 0.7078],
         [0.8318, 0.2095, 0.2037, 0.8718, 0.1484],
         [0.5897, 0.8910, 0.9870, 0.6202, 0.5690]]])

In [30]:
#Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3, 224, 224))  #colour channels (R, G, B), height, width 

print(random_image_size_tensor.shape)
random_image_size_tensor

torch.Size([3, 224, 224])


tensor([[[0.9931, 0.1083, 0.5516,  ..., 0.4743, 0.8533, 0.1574],
         [0.0021, 0.4009, 0.5548,  ..., 0.6686, 0.7962, 0.3938],
         [0.9478, 0.5516, 0.3012,  ..., 0.2287, 0.0934, 0.3226],
         ...,
         [0.6162, 0.8911, 0.4309,  ..., 0.4408, 0.3001, 0.4023],
         [0.1754, 0.9300, 0.5653,  ..., 0.4824, 0.8067, 0.7696],
         [0.5253, 0.1847, 0.1480,  ..., 0.8265, 0.0347, 0.1080]],

        [[0.9522, 0.4136, 0.8811,  ..., 0.5479, 0.0255, 0.8153],
         [0.4757, 0.8860, 0.3656,  ..., 0.5767, 0.7409, 0.3060],
         [0.1275, 0.4576, 0.2802,  ..., 0.3641, 0.3387, 0.6143],
         ...,
         [0.0109, 0.4212, 0.4310,  ..., 0.5213, 0.9464, 0.6092],
         [0.6944, 0.1117, 0.9787,  ..., 0.3288, 0.3486, 0.4076],
         [0.4254, 0.6665, 0.1163,  ..., 0.3001, 0.6237, 0.6133]],

        [[0.1553, 0.9886, 0.3617,  ..., 0.2466, 0.5562, 0.9215],
         [0.6511, 0.5326, 0.1162,  ..., 0.6325, 0.6084, 0.6822],
         [0.2847, 0.6450, 0.6953,  ..., 0.6636, 0.9305, 0.

## Zeros and ones

In [31]:
zeros_3d = torch.zeros(size=(3, 4, 4))
zeros_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [32]:
zeros = torch.zeros(size=(3, 4))

zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
ones = torch.ones(size=(3, 4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
#default data type for tensors
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [35]:
# Use torch.range

two_to_20 = torch.arange(2, 21)

two_to_20

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20])

In [36]:
torch.arange(start=0, end=100, step=2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [37]:
torch.arange(start=0, end=102, step=2)

tensor([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
         28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,
         56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,
         84,  86,  88,  90,  92,  94,  96,  98, 100])

### Creating tensors like

In [38]:
# Creating a tensor like the shape of another tensor

tensor_like_twenty = torch.zeros_like(input=two_to_20)

tensor_like_twenty

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
tensor_like_3d_random = torch.rand_like(input=random_tensor)

tensor_like_3d_random

tensor([[0.8708, 0.2961, 0.0451, 0.2847],
        [0.4701, 0.1214, 0.6153, 0.7859],
        [0.1516, 0.7099, 0.7018, 0.6816]])

In [40]:
#doesnt work because rand requires float not int
# torch.rand_like(input=TENSOR_2)

torch.ones_like(input=TENSOR_2)


tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]])

## Tensor Datatypes

**Note:** Dtype is one 3 common errors when running PyTorch for DL
1. Tensor is not right dtype
2. Tensor not right shape
3. Tensor not on right device 

In [41]:
float_32_tensor = torch.tensor([3.0, 6.0], dtype=None)

float_32_tensor

tensor([3., 6.])

In [42]:

#Still shows dtype as float because its the default dtype in torch
float_32_tensor.dtype

torch.float32

In [43]:
all_param_tensor = torch.tensor([
    [6, 7],
    [8, 9]
], dtype=None,  # datatype of data in the tensor
    device=None,  # default is cpu,could be changed to cuda
    requires_grad=False  # If you want the tensor to track gradients when the values are updated
)

In [44]:
float_16_tensor = float_32_tensor.type(torch.half)
# or
# float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6.], dtype=torch.float16)

In [45]:
#type casted to higher capacity dtype
(float_32_tensor * float_16_tensor).dtype

torch.float32

In [46]:
int_32_tensor = torch.tensor([3, 6], dtype=torch.int32)
int_32_tensor

tensor([3, 6], dtype=torch.int32)

In [47]:
float_32_tensor * int_32_tensor

tensor([ 9., 36.])

In [48]:
long_tensor = torch.tensor(data=([3, 6]), dtype=torch.long)
long_tensor

tensor([3, 6])

In [49]:
float_32_tensor * long_tensor

tensor([ 9., 36.])

### Getting info from tensor

1. Tensor is not right dtype - to get dtype from a tensor - use `tensor.dtype` 
2. Tensor not right shape - to get shape, use `tensor.shape`
3. Tensor not on right device - to get which device tensor is on, use `tensor.device` 

In [50]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3731, 0.8716, 0.3473, 0.7439],
        [0.9673, 0.1994, 0.7434, 0.9422],
        [0.5207, 0.4518, 0.2280, 0.1446]])

In [51]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.3731, 0.8716, 0.3473, 0.7439],
        [0.9673, 0.1994, 0.7434, 0.9422],
        [0.5207, 0.4518, 0.2280, 0.1446]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


In [52]:
#Note tensor shape and size are the same
#Size is just a func, while shape is an attribute

some_tensor.shape, some_tensor.size()

(torch.Size([3, 4]), torch.Size([3, 4]))

In [53]:
gpu_tensor = torch.rand(3, 4, device=torch.device('cuda'))



## Manipulating Tensors (Tensor Operations)

Ops include:
* Addition
* Subtraction
* Element-wise multiplication
* Matrix multiplication
* Division

In [54]:
test_tensor = torch.tensor(data=([1, 2, 3]))
test_tensor + 10

tensor([11, 12, 13])

In [55]:
test_tensor - 10

tensor([-9, -8, -7])

In [56]:
test_tensor * 10

tensor([10, 20, 30])

In [57]:
test_tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [58]:
test_tensor // 10

tensor([0, 0, 0])

In [59]:
torch.multiply(test_tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two main ways of multiplication:
1. Element-wise multiplication (e.g. matrix * scalar)
2. Matrix multiplication (dot product => a . b)

Matrix multiplication rules
1. The **inner dimensions** must match: 
* `(3,2) @ (3,2)` wont work
* `(3,2) @ (2,3)` will work
* `(2,3) @ (3,2)` will work
2. The resulting matrix will have the shape of the **outer dimensions**:
* `(3,2) @ (2,3)` -> `(3,3)`
* `(2,3) @ (3,2)` -> `(2,2)`

Generalizing:
**mxn.nxp = mxp**

cols of first matrix = rows of second matrix
Result will have rows of first and cols of second

In [60]:
mul_tensor = torch.tensor(data=(
    [1, 2, 3],
    [4, 5, 6])
)

mul_tensor_2 = torch.tensor(data=(
    [7, 8],
    [10, 11],
    [13, 14])
)

In [61]:
#Element-wise multiplication
print(mul_tensor, "*", mul_tensor)
print(f"Equals: {mul_tensor * mul_tensor}")

# Cant multiply element-wise because shape mismatch
# print(f"Equals: {mul_tensor * mul_tensor_2}")

tensor([[1, 2, 3],
        [4, 5, 6]]) * tensor([[1, 2, 3],
        [4, 5, 6]])
Equals: tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [62]:
#Matrix multiplication
torch.matmul(input=mul_tensor, other=mul_tensor_2)

tensor([[ 66,  72],
        [156, 171]])

In [63]:
torch.matmul(input=mul_tensor_2, other=mul_tensor)

tensor([[ 39,  54,  69],
        [ 54,  75,  96],
        [ 69,  96, 123]])

In [64]:
tensor_sca_1 = torch.tensor(data=([1, 2, 3]))



In [65]:
%%time
#Doesnt show it here but this is way faster for big tensor multiplications than a for loop
torch.matmul(tensor_sca_1, tensor_sca_1)

CPU times: total: 0 ns
Wall time: 2.22 ms


tensor(14)

In [66]:
%%time 
#Has to be first thing in cell
# The above cell is basically only doing a dot product between 2 vectors
sum = 0
for i in tensor_sca_1:
    sum += i * i
sum

# 1*1 + 2*2 + 3*3 

CPU times: total: 0 ns
Wall time: 1.47 ms


tensor(14)

In [67]:
# Another way of saying mat mul
tensor_sca_1 @ tensor_sca_1

tensor(14)

In [68]:
#This is working because it is being treated as a vector instead of a matrix
# If it considered it as a matrix of 1,3 then it would give an error
tensor_sca_1.shape

torch.Size([3])

In [69]:
shape_2_vector = torch.tensor(data=[[1, 2, 3]])
shape_2_vector.shape

torch.Size([1, 3])

In [70]:
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x3 and 1x3)
# torch.matmul(shape_2_vector, shape_2_vector)

In [71]:
# This works because it transposed the second vector making it 3x1
torch.matmul(shape_2_vector, shape_2_vector.T)

tensor([[14]])

#### One of the most common errors in DL : Shape errors

In [72]:
# Shapes for Matrix multiplication
Tensor_A = torch.tensor(data=[[1, 2, ],
                              [4, 5, ],
                              [7, 8, ]])

Tensor_B = torch.tensor(data=[[1, 2, ],
                              [3, 4, ],
                              [5, 6, ]])

In [73]:
Tensor_A.shape, Tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

Inner dimensions are different so cant multiply 

To fix our issue, we can **transpose** one of our matrices

A **transpose** switches the dimensions of our matrix

In [74]:
Tensor_B.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [75]:
Tensor_B

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [76]:
Tensor_B.shape, Tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [77]:
torch.matmul(Tensor_A, Tensor_B.T)

tensor([[ 5, 11, 17],
        [14, 32, 50],
        [23, 53, 83]])

In [78]:
torch.matmul(Tensor_A, Tensor_B.T).shape

torch.Size([3, 3])

## Tensor Aggregation

Finding min, max, sum, etc.



In [81]:
#Stacking 2 tensors to make a new tensor
tensor_agg = torch.stack([
    torch.arange(1, 6, 2),
    torch.arange(6, 11, 2)
])

tensor_agg

tensor([[ 1,  3,  5],
        [ 6,  8, 10]])

In [82]:
tensor_agg.shape

torch.Size([2, 3])

In [83]:
tensor_agg.min()

tensor(1)

In [84]:
tensor_agg.max()

tensor(10)

In [85]:
#Doesnt work because mean requires float dtype
# tensor_agg.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [86]:
torch.mean(tensor_agg.type(torch.float32))

tensor(5.5000)

In [88]:
#The above created a copy of the tensor in float, the original tensor still exists in int64 type (long)
tensor_agg.dtype

torch.int64

In [89]:
tensor_agg.sum()

tensor(33)

### Finding the index of max or min (Positional max or min)

In [90]:
#Index of min is 0
tensor_agg.argmin()

tensor(0)

In [91]:
# tensor_agg.argmax() gives 5, meaning the maximum value is at the 5th position in a flattened version of the tensor.
tensor_agg.argmax()

tensor(5)

In [95]:
# torch.unravel_index(flat_index, shape) converts this flat index into a 2D coordinate (row, column)
max_idx_flat = tensor_agg.argmax()
torch.unravel_index(max_idx_flat, tensor_agg.shape)

(tensor(1), tensor(2))

## Reshaping, Stacking, Squeezing and unsqueezing tensors

* Reshaping - Reshaping an input tensor into a defined shape
* View - Return a view of a tensor in a certain shape but keep the original tensor unchanged. But keep in mind view shares the same memory as the original so any change in it will result in change in tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack) (or stack by itself with input dim)
* Squeeze - Removes all `1` dimensions from the tensor
* Unsqueeze - Adds a `1` dimension to a tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way 

In [120]:
x = torch.arange(1., 10.)  #float

x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [99]:
#This wont work because we have 9 elements and we are trying to shape it into 1 row with 7 columns which wont fit
# x_reshape = x.reshape(1, 7)
# x_reshape, x_reshape.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [100]:
#Notice we added a new dimension (extra []), earlier shape was only 9
x_reshape = x.reshape(1, 9)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [101]:
#Would require 18 elements to fill this
# x_reshape = x.reshape(2, 9)
# x_reshape, x_reshape.shape

RuntimeError: shape '[2, 9]' is invalid for input of size 9

In [103]:
#9 rows and 1 column
x_reshape = x.reshape(9, 1)
x_reshape, x_reshape.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

Basically think this way, the product of dims is the number of elements that will fit

so if i have shape (4,3) I have 12 elements. These can be reshaped to any dimensions as long as their product is 12. e.g. (2,6) 

In [105]:
y = torch.tensor(data=([
    [1, 2, 3],
    [4, 5, 6],
    [6, 7, 8],
    [9, 10, 11]
]))

y, y.shape

(tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [ 6,  7,  8],
         [ 9, 10, 11]]),
 torch.Size([4, 3]))

In [106]:
y.reshape(2, 6), y.reshape(2, 6).shape

(tensor([[ 1,  2,  3,  4,  5,  6],
         [ 6,  7,  8,  9, 10, 11]]),
 torch.Size([2, 6]))

In [109]:
y.reshape(2, 1, 6), y.reshape(2, 1, 6).shape

(tensor([[[ 1,  2,  3,  4,  5,  6]],
 
         [[ 6,  7,  8,  9, 10, 11]]]),
 torch.Size([2, 1, 6]))

In [121]:
#Change the view
z = x.view(9, 1)
z, z.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [122]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [123]:
#Changed the first 2 rows of z to 5 for all columns
z[0:2, :] = 5

In [125]:
#Changing z changes x as well
x, z

(tensor([5., 5., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5.],
         [5.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]))

In [127]:
#Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
#Stacked vertically, as new rows
# x
# x
# x
# x
x_stacked

tensor([[5., 5., 3., 4., 5., 6., 7., 8., 9.],
        [5., 5., 3., 4., 5., 6., 7., 8., 9.],
        [5., 5., 3., 4., 5., 6., 7., 8., 9.],
        [5., 5., 3., 4., 5., 6., 7., 8., 9.]])

In [128]:
x_stacked = torch.stack([x, x, x, x], dim=1)
#Stacked horizontally, as new columns
# x x x x
x_stacked

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [134]:
x_reshape, x_reshape.shape

(tensor([[5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.]]),
 torch.Size([9, 1]))

In [135]:
p = x_reshape.squeeze()
p, p.shape

(tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.]), torch.Size([9]))

In [137]:
#unsqueeze adds a single dimension to a target tensor at a specific dim
p.unsqueeze(0), p.unsqueeze(0).shape

(tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.]]), torch.Size([1, 9]))

In [138]:
#unsqueeze adds a single dimension to a target tensor at a specific dim
p.unsqueeze(1), p.unsqueeze(1).shape

(tensor([[5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.]]),
 torch.Size([9, 1]))

In [139]:
p.unsqueeze(0).unsqueeze(0), p.unsqueeze(0).unsqueeze(0).shape

(tensor([[[5., 5., 5., 5., 5., 5., 5., 5., 5.]]]), torch.Size([1, 1, 9]))

In [140]:
p.unsqueeze(1).unsqueeze(1), p.unsqueeze(1).unsqueeze(1).shape

(tensor([[[5.]],
 
         [[5.]],
 
         [[5.]],
 
         [[5.]],
 
         [[5.]],
 
         [[5.]],
 
         [[5.]],
 
         [[5.]],
 
         [[5.]]]),
 torch.Size([9, 1, 1]))

In [142]:
#permute - Rearranges dims of a target tensor in a specified order
r = torch.rand(2, 3, 5)

r, r.shape

(tensor([[[0.2454, 0.1908, 0.9584, 0.4823, 0.8042],
          [0.5790, 0.1932, 0.0434, 0.2104, 0.5642],
          [0.4390, 0.9931, 0.9911, 0.3098, 0.8201]],
 
         [[0.7406, 0.2177, 0.7380, 0.0642, 0.5780],
          [0.9615, 0.4086, 0.3770, 0.8813, 0.1554],
          [0.6191, 0.1818, 0.0098, 0.3255, 0.8279]]]),
 torch.Size([2, 3, 5]))

In [144]:
# dim of index 2 (5) is at 0
# dim of index 0 (2) is at 1
# dim of index 1 (3) is at 2
torch.permute(r, (2, 0, 1)).shape

torch.Size([5, 2, 3])

### Indexing (selecting data from tensors)

Indexing with Pytorch is similar to NumPy

In [146]:
i = torch.arange(1, 10).reshape(1, 3, 3)

i, i.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [149]:
i[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [151]:
#Both are the same thing
i[0][0], i[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [152]:
i[0][0][0], i[0, 0, 0]

(tensor(1), tensor(1))

In [153]:
# You can use ":" to select  "all" of a target dimension
#from all the matrices, from all  the rows, select the 0th column
i[:, :, 0]

tensor([[1, 4, 7]])

In [154]:
#from all the matrices, from th e rows 0 to 1, select the 0th column
i[:, 0:2, 0]

tensor([[1, 4]])

In [155]:
#Get all values of 0 dim, but only the 1 index value of 1st and 2nd dim
i[:, 1, 1]

tensor([5])

In [156]:
#Get index 0 of 0th and 1st dimension and all values of 2nd dimension
i[0, 0, :]

tensor([1, 2, 3])

### PyTorch tensors and NumPy

* Data in NumPy array, but want it in Pytorch tensor -> `torch.from_numpy(ndarray)`
* Tensor to Numpy -> `torch.Tensor.numpy()`

In [158]:
npArray = np.arange(1., 8.)
npArray

array([1., 2., 3., 4., 5., 6., 7.])

In [160]:
torchTensor = torch.from_numpy(npArray)

torchTensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [167]:
#Note that torch's default float is float32, but np is 64 so to prevent lossy conversion it keeps it 64. We can change it explicitly though

torchTensor32 = torch.from_numpy(npArray).type(torch.float32)
torchTensor32, torchTensor32.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [168]:
#Deep copy, tensor is a new memory space
npArray = npArray+1
npArray,torchTensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [170]:
ttensor = torch.ones(7)
npTensor = torch.Tensor.numpy(ttensor)

ttensor,npTensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [171]:
#Deep copy this way as well, ndarray is a new memory space
ttensor = ttensor+1
npTensor,ttensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

## Reproducability (trying to take the random out of random)

In short NN learn by:

`start with random numbers -> perform tensor ops -> Update random numbers to represent certain features or patterns ->again ->again...`

To reduce the randomness, we can use the **random seed**

Essentially what it does is it gives a starting point or deterministic parameter for the random number generating algorithm ensuring that it always spits out the same numbers in the same sequence

Extra resources:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed


In [174]:
#Will give different random numbers everytime we run
torch.rand(3,3)

tensor([[0.5958, 0.9546, 0.8020],
        [0.4885, 0.7304, 0.6836],
        [0.5653, 0.9082, 0.7298]])

In [192]:
r1 = torch.rand(3,4)
r2 = torch.rand(3,4)

print(r1)
print(r2)
print(r1==r2)

tensor([[9.6083e-01, 6.5658e-01, 4.5299e-02, 7.8406e-01],
        [1.6308e-04, 9.6005e-01, 3.2690e-01, 5.5247e-02],
        [9.1119e-01, 8.8046e-01, 7.7628e-01, 5.6449e-01]])
tensor([[0.7427, 0.5554, 0.8484, 0.0341],
        [0.9879, 0.8145, 0.1475, 0.9693],
        [0.2131, 0.3344, 0.7464, 0.1872]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [201]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
r1 = torch.rand(3,4)
r1

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [202]:
#Think of it this way once we set the random seed it generates a list of numbers its going to output like 0.8,0.9,0.6..... So once we set it we will get those numbers anytime we want something random. Setting the seed again to the same value resets us to the beginning of the list, so we will generate the number at index 0 again
torch.manual_seed(RANDOM_SEED)

r2 = torch.rand(3,4)
r2

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [203]:
print(r1==r2)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors or general PyTorch objects in GPUs



In [204]:
print(torch.__version__)
print(torch.cuda.is_available())

2.4.1
True


In [205]:
#Setup Device agnostic code to run on gpu if available or cpu
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [211]:
#Count number of devices
print(torch.cuda.device_count())
print(torch.cuda.get_device_name())


1
NVIDIA GeForce RTX 4070 Laptop GPU


### Putting tensors and models on the GPU




In [212]:
#Default tensor is on cpu
cpu_tensor = torch.rand(3, 4)
print(cpu_tensor.device)

cpu


In [214]:
gpu_tensor = torch.rand(3, 4,device=device)
print(gpu_tensor.device)

cuda:0


In [215]:
#We can also move a tensor to the gpu
tensor_on_gpu = cpu_tensor.to(device)
print(tensor_on_gpu,tensor_on_gpu.device)

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]], device='cuda:0') cuda:0


In [216]:
#This still exists though, it created a copy of it on the gpu 
cpu_tensor,cpu_tensor.device

(tensor([[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]),
 device(type='cpu'))

In [218]:
#NumPy does not work with data on the gpu
# tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [220]:
#Moving back to cpu
# or tensor_on_gpu.to("cpu")
prodigal_son = tensor_on_gpu.cpu()
prodigal_son,prodigal_son.device

(tensor([[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]),
 device(type='cpu'))

In [221]:
prodigal_son.numpy()

array([[0.86940444, 0.5677153 , 0.74109405, 0.4294045 ],
       [0.8854429 , 0.57390445, 0.26658005, 0.62744915],
       [0.26963168, 0.44136357, 0.29692084, 0.8316855 ]], dtype=float32)